# Meta
name: 보이스씨어터 몸소리
description: 보이스씨어터 ‘몸MOM소리’는 소리가 몸과 맘과 자연을 이어주는 통로라는 것을 인식하고, 이를 바탕으로 소리 재료를 본격적으로 실험하여 창작한 작품으로 여러분과 공명하고자 합니다.
url: http://voicetheater.net
baseurl: ''

timezone: 'Asia/Seoul'
permalink: pretty

# Build
exclude:
  - .jekyll-metadata
  - .gitignore
  - .ruby-version
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

kramdown:
  input: GFM
  syntax_highlighter: rouge

# collections
collections:
  works:
    output: true
    permalink: /work/:path/
  courses:
    output: true
    permalink: /course/:path/

defaults:
  -
    scope:
      path: _works
    values:
      layout: work
  -
    scope:
      path: _courses
    values:
      layout: course
