# Meta
name: <span class="hidden-xs">보이스씨어터</span> 몸MOM소리
description: 보이스씨어터 ‘몸MOM소리’는 소리가 몸과 맘과 자연을 이어주는 통로라는 것을 인식하고, 이를 바탕으로 소리 재료를 본격적으로 실험하여 창작한 작품으로 여러분과 공명하고자 합니다.
url: http://voicetheater.net
baseurl: ''
address: 경기도 과천시 부림 4길 55, 2층
postal_code: 13830
email: momsori2777@hanmail.net

en:
  name: MOMSORI
  description:
  url: http://voicetheater.net/en/
  address: 55, Burim 4-gil, Gwacheon-si, Gyeonggi-do, 13830, Republic of Korea

timezone: 'Asia/Seoul'
permalink: pretty

# SEO
facebook:
  app_id: 618140558345676
  publisher: https://www.facebook.com/momsori
logo: momsori.gif
google_site_verification:
google_analytics: UA-81266340-3

# Build
exclude:
  - .jekyll-metadata
  - .gitignore
  - .ruby-version
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - TODO.md

sass:
  style: compressed

kramdown:
  input: GFM
  syntax_highlighter: rouge
  entity_output: :as_input
  hard_wrap: true

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

# collections
collections:
  works:
    output: true
    permalink: /work/:path/
  courses:
    output: true
    permalink: /course/:path/
  en_works:
    output: true
    permalink: /en/work/:path/

defaults:
  -
    scope:
      path: ""
    values:
      image:
        twitter:
        facebook:
  -
    scope:
      path: _works
    values:
      layout: work
  -
    scope:
      path: _courses
    values:
      layout: course
  -
    scope:
      path: _en_works
    values:
      layout: en/work
